### ISSUE TITLE
Verifier Improvements

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#192]
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/191
- [ ] https://github.com/didx-xyz/aries-cloudapi-python/issues/189
- [ ] https://github.com/didx-xyz/aries-cloudapi-python/issues/187
