### ISSUE TITLE
Version 1.0 release

### ISSUE THREAD

**Issue by ff137** [didx-xyz/aries-cloudapi-python#328]
- [x] Upgrade Starlette & FastAPI -- #318 
- [x] Fix redirects for webhooks -- #339 
- [x] ~~Fix parallel pytests~~ -- #324 (Won't do)
- [x] Implement Server-Sent Events for webhook events 
-- #311 
-- #345 
-- #357 
-- #360 
- [x] Implement Websocket PubSubClient for webhooks -- #362 
- [x] Improved logging throughout codebase -- #368 
- [x] Trust registry improvements:
-- Get schema by id -- #372 
-- Improve duplicate actor handling -- #377 
-- Use Postgres instead of SQLite DB -- #384
-- Migrate SQLAlchemy to v2 -- #385  
- [x] 0.8.1 ACA-Py agents -- #389 
- [x] 0.8.2 ACA-Py agents -- #395 
- [x] 0.9.0 ACA-Py agents -- #400 
- [x] #386 
- [x] Add style checking 
-- #399 
-- #405 
- [x] Support JSON-LD credentials
-- #414 
-- #418 
-- #424 
-- Support did:key + BBS signature type
-- Implement e2e tests of issuing/verifying JSON-LD credentials

**Comment by ff137** [comment]
Can maybe include: cleaning up of default log levels, and I was wondering about renaming some pods: e.g. `governance-ga-agent`

**Comment by lohanspies** [comment]
Regarding renaming the pods... think we can drop the `governance-` from all the pods.
Not sure how this might affect the CI/CD and SRE side of things. Maybe speak to Willem first
