### ISSUE TITLE
Ecosystem management

### ISSUE THREAD

**Issue by mrcbond88** [didx-xyz/aries-cloudapi-python#99]
## TODO

- [ ] #190
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/176
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/159
- [x] #157
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/186
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/176
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/185
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/141
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/143
- [x] https://github.com/didx-xyz/aries-cloudapi-python/issues/144

## Requirements

Required from API to spin up ecosystem partners:

- For issuers and verifiers
	- Create subwallet for ecosystem partners to be able to act as issuer, verifiers & members.
- For verifiers 
  - Add verifiers to trust registry in the role of verifier with enough context to make establish connections with/from yoma members.
- For issuers 
	  - When a partner onboards as an issuer, Yoma will automatically write a public DID for them.
	  - Provide schema list to ecosystem partners( as role of issuer). The endpoint exists and will call the schema list for partners to choose from.
	  - Once schema is chosen, allow ecosystem subwallets to write to ledger via transaction endorser protocol. (Only credential definitions)
- For all
	- Enforce the trust registry rules

**Comment by mrcbond88** [comment]
Working through Timo's endpoints, tests and create pubDID to see which ones are outstanding and which ones are not working. From there once we've got our ducks in a row, we'll be a lot quicker to move through this.
